In [1]:
import tensorflow as tf
print("TensorFlow version: ",tf.version.VERSION)

TensorFlow version:  2.1.0


In [2]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

11493376/11490434 [==============================] - 8s 1us/step


In [5]:
model =tf.keras.Sequential([
    tf.keras.layers.Flatten(input_shape=(28, 28)),
    tf.keras.layers.Dense(128,activation="relu"),
    tf.keras.layers.Dense(64,activation="relu"),
    tf.keras.layers.Dense(32,activation="tanh"),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10)   
])

'''
model_tst = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(units=128, activation="relu", name="h0"),
    tf.keras.layers.Dense(units=128, activation="relu", name="h1"),
    tf.keras.layers.Dense(units=128, activation="relu", name="h2"),
    tf.keras.layers.Dense(units=10, activation="softmax", name="output")
    ])
'''

In [6]:
predictions = model(x_train[:1]).numpy()
predictions


If you intended to run this layer in float32, you can safely ignore this warning. If in doubt, this warning is likely only an issue if you are porting a TensorFlow 1.X model to TensorFlow 2.

To change all layers to have dtype float64 by default, call `tf.keras.backend.set_floatx('float64')`. To change just this layer, pass dtype='float64' to the layer constructor. If you are the author of this layer, you can disable autocasting by passing autocast=False to the base Layer constructor.



array([[ 0.5805881 ,  0.6358318 ,  0.2853106 ,  0.30404866,  0.72358334,
        -0.56760824, -0.56587434,  0.05035911,  0.08061185,  0.2260989 ]],
      dtype=float32)

For each example the model returns a vector of "logits" or "log-odds" scores, one for each class. The tf.nn.softmax function converts these logits to "probabilities" for each class:

In [7]:
tf.nn.softmax(predictions).numpy()

array([[0.13803071, 0.14587058, 0.10273971, 0.104683  , 0.15924938,
        0.0437845 , 0.04386048, 0.08122696, 0.08372184, 0.09683292]],
      dtype=float32)

In [8]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [9]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [10]:
model.fit(x_train, y_train, epochs=6)

Train on 60000 samples
Epoch 1/6
60000/60000 [==============================] - 9s 149us/sample - loss: 0.2647 - accuracy: 0.9262
Epoch 2/6
60000/60000 [==============================] - 9s 143us/sample - loss: 0.1155 - accuracy: 0.9658
Epoch 3/6
60000/60000 [==============================] - 10s 169us/sample - loss: 0.0830 - accuracy: 0.9750
Epoch 4/6
60000/60000 [==============================] - 11s 188us/sample - loss: 0.0665 - accuracy: 0.9805
Epoch 5/6
60000/60000 [==============================] - 7s 120us/sample - loss: 0.0547 - accuracy: 0.9834
Epoch 6/6
60000/60000 [==============================] - 7s 124us/sample - loss: 0.0473 - accuracy: 0.9858


In [11]:
model.evaluate(x_test,  y_test, verbose=2)

10000/10000 - 1s - loss: 0.0858 - accuracy: 0.9779


[0.08577657029847614, 0.9779]

In [12]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[9.45528063e-06, 3.00997835e-05, 1.28735424e-04, 6.01666863e-04,
        1.03114571e-05, 2.97657971e-05, 4.06078607e-06, 9.99077320e-01,
        3.41484179e-06, 1.05178464e-04],
       [4.77244866e-05, 3.82793005e-05, 9.99439061e-01, 2.95192935e-04,
        9.04796434e-06, 4.56355792e-07, 3.24855464e-05, 1.99011865e-05,
        1.17323485e-04, 3.88946461e-07],
       [3.61603679e-06, 9.99866843e-01, 2.70334226e-06, 1.29740442e-06,
        5.92631986e-05, 1.23295615e-06, 3.07575719e-05, 1.76808899e-05,
        1.28015163e-05, 3.91242293e-06],
       [9.99869585e-01, 1.32974537e-06, 3.44884538e-05, 8.06028129e-06,
        6.06639742e-06, 4.89734703e-06, 4.05456631e-05, 1.95892389e-05,
        3.10190148e-06, 1.23600576e-05],
       [3.47187779e-05, 1.87754795e-05, 9.50709455e-06, 4.90583307e-06,
        9.98473942e-01, 3.01918681e-06, 3.66373060e-05, 7.13407644e-05,
        6.52970175e-06, 1.34063221e-03]], dtype=float32)>